// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAzLVkcfN-GLz_NfRcLKcOvEK0hneRcEnk',
    appId: '1:266180302237:web:5c4fd4e16ae017ca620b74',
    messagingSenderId: '266180302237',
    projectId: 'chatapp-dedcc',
    authDomain: 'chatapp-dedcc.firebaseapp.com',
    storageBucket: 'chatapp-dedcc.appspot.com',
    measurementId: 'G-4M88BPPGTX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyClQcXNvqIElwAw1krHZ7knp5jR5VpB-Qg',
    appId: '1:266180302237:android:b74af9e5d85c695e620b74',
    messagingSenderId: '266180302237',
    projectId: 'chatapp-dedcc',
    storageBucket: 'chatapp-dedcc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB6eL-hprJo3KrActOjn-CQZDA0u7x-Eiw',
    appId: '1:266180302237:ios:f92aaaa824de1300620b74',
    messagingSenderId: '266180302237',
    projectId: 'chatapp-dedcc',
    storageBucket: 'chatapp-dedcc.appspot.com',
    iosBundleId: 'com.example.socialMedia',
  );
}
